version: "3"
services:
  app:
    container_name: registsupport_app
    build:
      context: ../../
      dockerfile: ./docker/production/java/Dockerfile
    image: local.u-gakugei.ac.jp/registsupport_app

  mysql:
    container_name: registsupport_db
    build:
      context: ../../
      dockerfile: ./docker/production/mysql/Dockerfile
    image: local.u-gakugei.ac.jp/registsupport_db
